[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_MAPBOX_TOKEN = ""
  VITE_SUPABASE_URL = "https://wfspbewhxxklgilaofgh.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmc3BiZXdoeHhrbGdpbGFvZmdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzY5MDcsImV4cCI6MjA1ODUxMjkwN30.Fwdz43TET0DJIflkQgIzLdKOdvHSyqefBXvWL20UMj8"

# Configure secrets scanning
[secrets]
  scan = true
  omit_keys = ["VITE_MAPBOX_TOKEN", "VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]
  omit_paths = ["dist/**"] 