[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning
[secrets]
  scan = true
  omit_keys = ["VITE_MAPBOX_TOKEN", "VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]
  omit_paths = ["dist/**"]

# Environment variables configuration
[build.environment]
  NODE_VERSION = "18"
  VITE_MAPBOX_TOKEN = ""
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = "" 