[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Disable secrets scanning for our environment variables
[secrets]
  scan = true
  omit_keys = ["VITE_MAPBOX_TOKEN", "VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"] 